[general]
import = [
  "~/.config/alacritty/themes/snazzy.toml",
]

[window]
dynamic_padding = true
padding = { x = 16, y = 14 }
decorations = "none"
opacity = 0.9
blur = true
startup_mode = "Maximized"

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/opt/homebrew/bin/zellij"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
size = 13
# offset = { y = 7 }
